version: '3.9'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    container_name: dev_template_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: super-secure-password
    ports:
      - "27017:27017"
